### ISSUE TITLE
Use long polling

### ISSUE THREAD

**Issue by ulich** [MFineOpenSource/n8n-nodes-aws-sqs-trigger#1]
Instead of using `setInterval()`, could you specify `WaitTimeSeconds` in the receive message request and set this to e.g. 20s instead? Then do the request in an endless loop. This will save resources (not doing too many requests in a short amount of time without any resulting messages) and also make the consumption of messages close to real time because the API call will return as soon as one message is available

**Comment by matthewkayy** [comment]
@ulich This repo was a copy (with no credit) of my initial PR I raised against the main [n8n repo](https://github.com/n8n-io/n8n/pull/2933)

I've since published a published a community node which has had long polling contributed to it: [https://www.npmjs.com/package/@mkayy/n8n-nodes-aws-sqs-trigger](npmjs.com/package/@mkayy/n8n-nodes-aws-sqs-trigger)

Hope this helps!

**Comment by ulich** [comment]
ah great, thanks I'll check it out
